# Site settings
title: wildcard.js
email: hello@wildcardjs.tech
url: wildcardjs.tech
description: "We are wildcard."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/wildcard_js
  - title: github
    url: https://github.com/wildcard-js
  - title: slack
    url: https://wildcardjs-slack.herokuapp.com/

# Build settings
markdown: kramdown
permalink: pretty
